/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.AccessToken = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AccessToken model module.
   * @module model/AccessToken
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>AccessToken</code>.
   * @alias module:model/AccessToken
   * @class
   * @param accessLevel {module:model/AccessToken.AccessLevelEnum} Access which this Token grants
   * @param name {String} Filename
   */
  var exports = function(accessLevel, name) {
    var _this = this;

    _this['AccessLevel'] = accessLevel;
    _this['Name'] = name;

  };

  /**
   * Constructs a <code>AccessToken</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccessToken} obj Optional instance to populate.
   * @return {module:model/AccessToken} The populated <code>AccessToken</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('AccessLevel')) {
        obj['AccessLevel'] = ApiClient.convertToType(data['AccessLevel'], 'String');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('LastUse')) {
        obj['LastUse'] = ApiClient.convertToType(data['LastUse'], 'Date');
      }
    }
    return obj;
  }

  /**
   * Access which this Token grants
   * @member {module:model/AccessToken.AccessLevelEnum} AccessLevel
   */
  exports.prototype['AccessLevel'] = undefined;
  /**
   * Filename
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * When was this AccessToken used last
   * @member {Date} LastUse
   */
  exports.prototype['LastUse'] = undefined;


  /**
   * Allowed values for the <code>AccessLevel</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AccessLevelEnum = {
    /**
     * value: "None"
     * @const
     */
    "None": "None",
    /**
     * value: "ViewAccount"
     * @const
     */
    "ViewAccount": "ViewAccount",
    /**
     * value: "ViewContacts"
     * @const
     */
    "ViewContacts": "ViewContacts",
    /**
     * value: "ViewForms"
     * @const
     */
    "ViewForms": "ViewForms",
    /**
     * value: "ViewTemplates"
     * @const
     */
    "ViewTemplates": "ViewTemplates",
    /**
     * value: "ViewCampaigns"
     * @const
     */
    "ViewCampaigns": "ViewCampaigns",
    /**
     * value: "ViewChannels"
     * @const
     */
    "ViewChannels": "ViewChannels",
    /**
     * value: "ViewJourneys"
     * @const
     */
    "ViewJourneys": "ViewJourneys",
    /**
     * value: "ViewSurveys"
     * @const
     */
    "ViewSurveys": "ViewSurveys",
    /**
     * value: "ViewSettings"
     * @const
     */
    "ViewSettings": "ViewSettings",
    /**
     * value: "ViewBilling"
     * @const
     */
    "ViewBilling": "ViewBilling",
    /**
     * value: "ViewSubAccounts"
     * @const
     */
    "ViewSubAccounts": "ViewSubAccounts",
    /**
     * value: "ViewUsers"
     * @const
     */
    "ViewUsers": "ViewUsers",
    /**
     * value: "ViewFiles"
     * @const
     */
    "ViewFiles": "ViewFiles",
    /**
     * value: "ViewReports"
     * @const
     */
    "ViewReports": "ViewReports",
    /**
     * value: "ModifyAccount"
     * @const
     */
    "ModifyAccount": "ModifyAccount",
    /**
     * value: "ModifyContacts"
     * @const
     */
    "ModifyContacts": "ModifyContacts",
    /**
     * value: "ModifyForms"
     * @const
     */
    "ModifyForms": "ModifyForms",
    /**
     * value: "ModifyTemplates"
     * @const
     */
    "ModifyTemplates": "ModifyTemplates",
    /**
     * value: "ModifyCampaigns"
     * @const
     */
    "ModifyCampaigns": "ModifyCampaigns",
    /**
     * value: "ModifyChannels"
     * @const
     */
    "ModifyChannels": "ModifyChannels",
    /**
     * value: "ModifyJourneys"
     * @const
     */
    "ModifyJourneys": "ModifyJourneys",
    /**
     * value: "ModifySurveys"
     * @const
     */
    "ModifySurveys": "ModifySurveys",
    /**
     * value: "ModifyFiles"
     * @const
     */
    "ModifyFiles": "ModifyFiles",
    /**
     * value: "Export"
     * @const
     */
    "Export": "Export",
    /**
     * value: "SendSmtp"
     * @const
     */
    "SendSmtp": "SendSmtp",
    /**
     * value: "SendSMS"
     * @const
     */
    "SendSMS": "SendSMS",
    /**
     * value: "ModifySettings"
     * @const
     */
    "ModifySettings": "ModifySettings",
    /**
     * value: "ModifyBilling"
     * @const
     */
    "ModifyBilling": "ModifyBilling",
    /**
     * value: "ModifyProfile"
     * @const
     */
    "ModifyProfile": "ModifyProfile",
    /**
     * value: "ModifySubAccounts"
     * @const
     */
    "ModifySubAccounts": "ModifySubAccounts",
    /**
     * value: "ModifyUsers"
     * @const
     */
    "ModifyUsers": "ModifyUsers",
    /**
     * value: "Security"
     * @const
     */
    "Security": "Security",
    /**
     * value: "ModifyLanguage"
     * @const
     */
    "ModifyLanguage": "ModifyLanguage",
    /**
     * value: "ViewSupport"
     * @const
     */
    "ViewSupport": "ViewSupport",
    /**
     * value: "SendHttp"
     * @const
     */
    "SendHttp": "SendHttp",
    /**
     * value: "Modify2FA"
     * @const
     */
    "Modify2FA": "Modify2FA",
    /**
     * value: "ModifySupport"
     * @const
     */
    "ModifySupport": "ModifySupport",
    /**
     * value: "ViewCustomFields"
     * @const
     */
    "ViewCustomFields": "ViewCustomFields",
    /**
     * value: "ModifyCustomFields"
     * @const
     */
    "ModifyCustomFields": "ModifyCustomFields",
    /**
     * value: "ModifyWebNotifications"
     * @const
     */
    "ModifyWebNotifications": "ModifyWebNotifications",
    /**
     * value: "ExtendedLogs"
     * @const
     */
    "ExtendedLogs": "ExtendedLogs"  };


  return exports;
}));


