/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BodyPart'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BodyPart'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.Body = factory(root.ElasticemailRestfulApi.ApiClient, root.ElasticemailRestfulApi.BodyPart);
  }
}(this, function(ApiClient, BodyPart) {
  'use strict';




  /**
   * The Body model module.
   * @module model/Body
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>Body</code>.
   * @alias module:model/Body
   * @class
   * @param subject {String} Default subject of email.
   * @param parts {Array.<module:model/BodyPart>} 
   */
  var exports = function(subject, parts) {
    var _this = this;

    _this['Subject'] = subject;
    _this['Parts'] = parts;
  };

  /**
   * Constructs a <code>Body</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Body} obj Optional instance to populate.
   * @return {module:model/Body} The populated <code>Body</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Subject')) {
        obj['Subject'] = ApiClient.convertToType(data['Subject'], 'String');
      }
      if (data.hasOwnProperty('Parts')) {
        obj['Parts'] = ApiClient.convertToType(data['Parts'], [BodyPart]);
      }
    }
    return obj;
  }

  /**
   * Default subject of email.
   * @member {String} Subject
   */
  exports.prototype['Subject'] = undefined;
  /**
   * @member {Array.<module:model/BodyPart>} Parts
   */
  exports.prototype['Parts'] = undefined;



  return exports;
}));


