/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.CampaignListPayload = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CampaignListPayload model module.
   * @module model/CampaignListPayload
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>CampaignListPayload</code>.
   * @alias module:model/CampaignListPayload
   * @class
   * @param campaignName {String} 
   * @param listName {String} Name of your list.
   * @param statuses {Array.<module:model/CampaignListPayload.StatusesEnum>} List of comma separated message statuses: 0 for all, 1 for ReadyToSend, 2 for InProgress, 4 for Bounced, 5 for Sent, 6 for Opened, 7 for Clicked, 8 for Unsubscribed, 9 for Abuse Report
   */
  var exports = function(campaignName, listName, statuses) {
    var _this = this;

    _this['CampaignName'] = campaignName;
    _this['ListName'] = listName;
    _this['Statuses'] = statuses;
  };

  /**
   * Constructs a <code>CampaignListPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CampaignListPayload} obj Optional instance to populate.
   * @return {module:model/CampaignListPayload} The populated <code>CampaignListPayload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('CampaignName')) {
        obj['CampaignName'] = ApiClient.convertToType(data['CampaignName'], 'String');
      }
      if (data.hasOwnProperty('ListName')) {
        obj['ListName'] = ApiClient.convertToType(data['ListName'], 'String');
      }
      if (data.hasOwnProperty('Statuses')) {
        obj['Statuses'] = ApiClient.convertToType(data['Statuses'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} CampaignName
   */
  exports.prototype['CampaignName'] = undefined;
  /**
   * Name of your list.
   * @member {String} ListName
   */
  exports.prototype['ListName'] = undefined;
  /**
   * List of comma separated message statuses: 0 for all, 1 for ReadyToSend, 2 for InProgress, 4 for Bounced, 5 for Sent, 6 for Opened, 7 for Clicked, 8 for Unsubscribed, 9 for Abuse Report
   * @member {Array.<module:model/CampaignListPayload.StatusesEnum>} Statuses
   */
  exports.prototype['Statuses'] = undefined;


  /**
   * Allowed values for the <code>statuses</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusesEnum = {
    /**
     * value: "All"
     * @const
     */
    "All": "All",
    /**
     * value: "ReadyToSend"
     * @const
     */
    "ReadyToSend": "ReadyToSend",
    /**
     * value: "WaitingToRetry"
     * @const
     */
    "WaitingToRetry": "WaitingToRetry",
    /**
     * value: "Sending"
     * @const
     */
    "Sending": "Sending",
    /**
     * value: "Error"
     * @const
     */
    "Error": "Error",
    /**
     * value: "Sent"
     * @const
     */
    "Sent": "Sent",
    /**
     * value: "Opened"
     * @const
     */
    "Opened": "Opened",
    /**
     * value: "Clicked"
     * @const
     */
    "Clicked": "Clicked",
    /**
     * value: "Unsubscribed"
     * @const
     */
    "Unsubscribed": "Unsubscribed",
    /**
     * value: "AbuseReport"
     * @const
     */
    "AbuseReport": "AbuseReport"  };


  return exports;
}));


