/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CampaignOptions', 'model/CampaignRecipient', 'model/CampaignTemplate', 'model/TrackingOptions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CampaignOptions'), require('./CampaignRecipient'), require('./CampaignTemplate'), require('./TrackingOptions'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.Campaign = factory(root.ElasticemailRestfulApi.ApiClient, root.ElasticemailRestfulApi.CampaignOptions, root.ElasticemailRestfulApi.CampaignRecipient, root.ElasticemailRestfulApi.CampaignTemplate, root.ElasticemailRestfulApi.TrackingOptions);
  }
}(this, function(ApiClient, CampaignOptions, CampaignRecipient, CampaignTemplate, TrackingOptions) {
  'use strict';




  /**
   * The Campaign model module.
   * @module model/Campaign
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>Campaign</code>.
   * @alias module:model/Campaign
   * @class
   * @param campaignTemplate {module:model/CampaignTemplate} 
   * @param name {String} Filename
   * @param status {module:model/Campaign.StatusEnum} Name of status: Active, Engaged, Inactive, Abuse, Bounced, Unsubscribed.
   * @param targets {module:model/CampaignRecipient} 
   * @param trackingOptions {module:model/TrackingOptions} 
   * @param options {module:model/CampaignOptions} 
   */
  var exports = function(campaignTemplate, name, status, targets, trackingOptions, options) {
    var _this = this;

    _this['CampaignTemplate'] = campaignTemplate;
    _this['Name'] = name;
    _this['Status'] = status;
    _this['Targets'] = targets;
    _this['TrackingOptions'] = trackingOptions;
    _this['Options'] = options;
  };

  /**
   * Constructs a <code>Campaign</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Campaign} obj Optional instance to populate.
   * @return {module:model/Campaign} The populated <code>Campaign</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('CampaignTemplate')) {
        obj['CampaignTemplate'] = CampaignTemplate.constructFromObject(data['CampaignTemplate']);
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('Status')) {
        obj['Status'] = ApiClient.convertToType(data['Status'], 'String');
      }
      if (data.hasOwnProperty('Targets')) {
        obj['Targets'] = CampaignRecipient.constructFromObject(data['Targets']);
      }
      if (data.hasOwnProperty('TrackingOptions')) {
        obj['TrackingOptions'] = TrackingOptions.constructFromObject(data['TrackingOptions']);
      }
      if (data.hasOwnProperty('Options')) {
        obj['Options'] = CampaignOptions.constructFromObject(data['Options']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CampaignTemplate} CampaignTemplate
   */
  exports.prototype['CampaignTemplate'] = undefined;
  /**
   * Filename
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * Name of status: Active, Engaged, Inactive, Abuse, Bounced, Unsubscribed.
   * @member {module:model/Campaign.StatusEnum} Status
   */
  exports.prototype['Status'] = undefined;
  /**
   * @member {module:model/CampaignRecipient} Targets
   */
  exports.prototype['Targets'] = undefined;
  /**
   * @member {module:model/TrackingOptions} TrackingOptions
   */
  exports.prototype['TrackingOptions'] = undefined;
  /**
   * @member {module:model/CampaignOptions} Options
   */
  exports.prototype['Options'] = undefined;


  /**
   * Allowed values for the <code>Status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "Deleted"
     * @const
     */
    "Deleted": "Deleted",
    /**
     * value: "Active"
     * @const
     */
    "Active": "Active",
    /**
     * value: "Processing"
     * @const
     */
    "Processing": "Processing",
    /**
     * value: "Sending"
     * @const
     */
    "Sending": "Sending",
    /**
     * value: "Completed"
     * @const
     */
    "Completed": "Completed",
    /**
     * value: "Paused"
     * @const
     */
    "Paused": "Paused",
    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",
    /**
     * value: "Draft"
     * @const
     */
    "Draft": "Draft"  };


  return exports;
}));


