/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContactUnsubscribeReasonCounts'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ContactUnsubscribeReasonCounts'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.ContactStats = factory(root.ElasticemailRestfulApi.ApiClient, root.ElasticemailRestfulApi.ContactUnsubscribeReasonCounts);
  }
}(this, function(ApiClient, ContactUnsubscribeReasonCounts) {
  'use strict';




  /**
   * The ContactStats model module.
   * @module model/ContactStats
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>ContactStats</code>.
   * 
   * @alias module:model/ContactStats
   * @class
   * @param engaged {Number} Number of engaged contacts
   * @param active {Number} Number of active contacts
   * @param complaint {Number} Number of complaint messages
   * @param unsubscribed {module:model/ContactUnsubscribeReasonCounts} 
   * @param bounced {Number} Number of bounced messages
   * @param inactive {Number} Number of inactive contacts
   * @param transactional {Number} Number of transactional contacts
   * @param stale {Number} 
   * @param notConfirmed {Number} 
   */
  var exports = function(engaged, active, complaint, unsubscribed, bounced, inactive, transactional, stale, notConfirmed) {
    var _this = this;

    _this['Engaged'] = engaged;
    _this['Active'] = active;
    _this['Complaint'] = complaint;
    _this['Unsubscribed'] = unsubscribed;
    _this['Bounced'] = bounced;
    _this['Inactive'] = inactive;
    _this['Transactional'] = transactional;
    _this['Stale'] = stale;
    _this['NotConfirmed'] = notConfirmed;
  };

  /**
   * Constructs a <code>ContactStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContactStats} obj Optional instance to populate.
   * @return {module:model/ContactStats} The populated <code>ContactStats</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Engaged')) {
        obj['Engaged'] = ApiClient.convertToType(data['Engaged'], 'Number');
      }
      if (data.hasOwnProperty('Active')) {
        obj['Active'] = ApiClient.convertToType(data['Active'], 'Number');
      }
      if (data.hasOwnProperty('Complaint')) {
        obj['Complaint'] = ApiClient.convertToType(data['Complaint'], 'Number');
      }
      if (data.hasOwnProperty('Unsubscribed')) {
        obj['Unsubscribed'] = ContactUnsubscribeReasonCounts.constructFromObject(data['Unsubscribed']);
      }
      if (data.hasOwnProperty('Bounced')) {
        obj['Bounced'] = ApiClient.convertToType(data['Bounced'], 'Number');
      }
      if (data.hasOwnProperty('Inactive')) {
        obj['Inactive'] = ApiClient.convertToType(data['Inactive'], 'Number');
      }
      if (data.hasOwnProperty('Transactional')) {
        obj['Transactional'] = ApiClient.convertToType(data['Transactional'], 'Number');
      }
      if (data.hasOwnProperty('Stale')) {
        obj['Stale'] = ApiClient.convertToType(data['Stale'], 'Number');
      }
      if (data.hasOwnProperty('NotConfirmed')) {
        obj['NotConfirmed'] = ApiClient.convertToType(data['NotConfirmed'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Number of engaged contacts
   * @member {Number} Engaged
   */
  exports.prototype['Engaged'] = undefined;
  /**
   * Number of active contacts
   * @member {Number} Active
   */
  exports.prototype['Active'] = undefined;
  /**
   * Number of complaint messages
   * @member {Number} Complaint
   */
  exports.prototype['Complaint'] = undefined;
  /**
   * @member {module:model/ContactUnsubscribeReasonCounts} Unsubscribed
   */
  exports.prototype['Unsubscribed'] = undefined;
  /**
   * Number of bounced messages
   * @member {Number} Bounced
   */
  exports.prototype['Bounced'] = undefined;
  /**
   * Number of inactive contacts
   * @member {Number} Inactive
   */
  exports.prototype['Inactive'] = undefined;
  /**
   * Number of transactional contacts
   * @member {Number} Transactional
   */
  exports.prototype['Transactional'] = undefined;
  /**
   * @member {Number} Stale
   */
  exports.prototype['Stale'] = undefined;
  /**
   * @member {Number} NotConfirmed
   */
  exports.prototype['NotConfirmed'] = undefined;



  return exports;
}));


