/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.ContactUpdatePayload = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ContactUpdatePayload model module.
   * @module model/ContactUpdatePayload
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>ContactUpdatePayload</code>.
   * 
   * @alias module:model/ContactUpdatePayload
   * @class
   * @param email {String} Proper email address.
   * @param firstName {String} First name.
   * @param lastName {String} Last name.
   * @param field {Object.<String, String>} 
   * @param customFields {String} Custom contact field like firstname, lastname, city etc. JSON serialized text like { \"city\":\"london\" } 
   * @param clearRestOfFields {Boolean} States if the fields that were omitted in this request are to be reset or should they be left with their current value
   */
  var exports = function(email, firstName, lastName, field, customFields, clearRestOfFields) {
    var _this = this;

    _this['Email'] = email;
    _this['FirstName'] = firstName;

    _this['LastName'] = lastName;
    _this['Field'] = field;
    _this['CustomFields'] = customFields;
    _this['ClearRestOfFields'] = clearRestOfFields;
  };

  /**
   * Constructs a <code>ContactUpdatePayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContactUpdatePayload} obj Optional instance to populate.
   * @return {module:model/ContactUpdatePayload} The populated <code>ContactUpdatePayload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Email')) {
        obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
      }
      if (data.hasOwnProperty('FirstName')) {
        obj['FirstName'] = ApiClient.convertToType(data['FirstName'], 'String');
      }
      if (data.hasOwnProperty('Activate')) {
        obj['Activate'] = ApiClient.convertToType(data['Activate'], 'Boolean');
      }
      if (data.hasOwnProperty('LastName')) {
        obj['LastName'] = ApiClient.convertToType(data['LastName'], 'String');
      }
      if (data.hasOwnProperty('Field')) {
        obj['Field'] = ApiClient.convertToType(data['Field'], {'String': 'String'});
      }
      if (data.hasOwnProperty('CustomFields')) {
        obj['CustomFields'] = ApiClient.convertToType(data['CustomFields'], 'String');
      }
      if (data.hasOwnProperty('ClearRestOfFields')) {
        obj['ClearRestOfFields'] = ApiClient.convertToType(data['ClearRestOfFields'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Proper email address.
   * @member {String} Email
   */
  exports.prototype['Email'] = undefined;
  /**
   * First name.
   * @member {String} FirstName
   */
  exports.prototype['FirstName'] = undefined;
  /**
   * True, if Contact should be activated. Otherwise, false
   * @member {Boolean} Activate
   */
  exports.prototype['Activate'] = undefined;
  /**
   * Last name.
   * @member {String} LastName
   */
  exports.prototype['LastName'] = undefined;
  /**
   * @member {Object.<String, String>} Field
   */
  exports.prototype['Field'] = undefined;
  /**
   * Custom contact field like firstname, lastname, city etc. JSON serialized text like { \"city\":\"london\" } 
   * @member {String} CustomFields
   */
  exports.prototype['CustomFields'] = undefined;
  /**
   * States if the fields that were omitted in this request are to be reset or should they be left with their current value
   * @member {Boolean} ClearRestOfFields
   */
  exports.prototype['ClearRestOfFields'] = undefined;



  return exports;
}));


