/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EmailJobFailedStatus'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EmailJobFailedStatus'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.EmailJobStatus = factory(root.ElasticemailRestfulApi.ApiClient, root.ElasticemailRestfulApi.EmailJobFailedStatus);
  }
}(this, function(ApiClient, EmailJobFailedStatus) {
  'use strict';




  /**
   * The EmailJobStatus model module.
   * @module model/EmailJobStatus
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>EmailJobStatus</code>.
   * @alias module:model/EmailJobStatus
   * @class
   * @param ID {String} ID number of your attachment
   * @param status {String} Name of status: submitted, complete, in_progress
   * @param recipientsCount {Number} 
   * @param failed {Array.<module:model/EmailJobFailedStatus>} 
   * @param failedCount {Number} Total emails failed.
   * @param sent {Array.<String>} 
   * @param sentCount {Number} Total emails sent.
   * @param delivered {Array.<String>} Number of delivered messages
   * @param deliveredCount {Number} 
   * @param pending {Array.<String>} 
   * @param pendingCount {Number} 
   * @param opened {Array.<String>} Number of opened messages
   * @param openedCount {Number} Total emails opened.
   * @param clicked {Array.<String>} Number of clicked messages
   * @param clickedCount {Number} Total emails clicked
   * @param unsubscribed {Array.<String>} Number of unsubscribed messages
   * @param unsubscribedCount {Number} Total emails unsubscribed
   * @param abuseReports {Array.<String>} 
   * @param abuseReportsCount {Number} 
   * @param messageIDs {Array.<String>} List of all MessageIDs for this job.
   */
  var exports = function(ID, status, recipientsCount, failed, failedCount, sent, sentCount, delivered, deliveredCount, pending, pendingCount, opened, openedCount, clicked, clickedCount, unsubscribed, unsubscribedCount, abuseReports, abuseReportsCount, messageIDs) {
    var _this = this;

    _this['ID'] = ID;
    _this['Status'] = status;
    _this['RecipientsCount'] = recipientsCount;
    _this['Failed'] = failed;
    _this['FailedCount'] = failedCount;
    _this['Sent'] = sent;
    _this['SentCount'] = sentCount;
    _this['Delivered'] = delivered;
    _this['DeliveredCount'] = deliveredCount;
    _this['Pending'] = pending;
    _this['PendingCount'] = pendingCount;
    _this['Opened'] = opened;
    _this['OpenedCount'] = openedCount;
    _this['Clicked'] = clicked;
    _this['ClickedCount'] = clickedCount;
    _this['Unsubscribed'] = unsubscribed;
    _this['UnsubscribedCount'] = unsubscribedCount;
    _this['AbuseReports'] = abuseReports;
    _this['AbuseReportsCount'] = abuseReportsCount;
    _this['MessageIDs'] = messageIDs;
  };

  /**
   * Constructs a <code>EmailJobStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmailJobStatus} obj Optional instance to populate.
   * @return {module:model/EmailJobStatus} The populated <code>EmailJobStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ID')) {
        obj['ID'] = ApiClient.convertToType(data['ID'], 'String');
      }
      if (data.hasOwnProperty('Status')) {
        obj['Status'] = ApiClient.convertToType(data['Status'], 'String');
      }
      if (data.hasOwnProperty('RecipientsCount')) {
        obj['RecipientsCount'] = ApiClient.convertToType(data['RecipientsCount'], 'Number');
      }
      if (data.hasOwnProperty('Failed')) {
        obj['Failed'] = ApiClient.convertToType(data['Failed'], [EmailJobFailedStatus]);
      }
      if (data.hasOwnProperty('FailedCount')) {
        obj['FailedCount'] = ApiClient.convertToType(data['FailedCount'], 'Number');
      }
      if (data.hasOwnProperty('Sent')) {
        obj['Sent'] = ApiClient.convertToType(data['Sent'], ['String']);
      }
      if (data.hasOwnProperty('SentCount')) {
        obj['SentCount'] = ApiClient.convertToType(data['SentCount'], 'Number');
      }
      if (data.hasOwnProperty('Delivered')) {
        obj['Delivered'] = ApiClient.convertToType(data['Delivered'], ['String']);
      }
      if (data.hasOwnProperty('DeliveredCount')) {
        obj['DeliveredCount'] = ApiClient.convertToType(data['DeliveredCount'], 'Number');
      }
      if (data.hasOwnProperty('Pending')) {
        obj['Pending'] = ApiClient.convertToType(data['Pending'], ['String']);
      }
      if (data.hasOwnProperty('PendingCount')) {
        obj['PendingCount'] = ApiClient.convertToType(data['PendingCount'], 'Number');
      }
      if (data.hasOwnProperty('Opened')) {
        obj['Opened'] = ApiClient.convertToType(data['Opened'], ['String']);
      }
      if (data.hasOwnProperty('OpenedCount')) {
        obj['OpenedCount'] = ApiClient.convertToType(data['OpenedCount'], 'Number');
      }
      if (data.hasOwnProperty('Clicked')) {
        obj['Clicked'] = ApiClient.convertToType(data['Clicked'], ['String']);
      }
      if (data.hasOwnProperty('ClickedCount')) {
        obj['ClickedCount'] = ApiClient.convertToType(data['ClickedCount'], 'Number');
      }
      if (data.hasOwnProperty('Unsubscribed')) {
        obj['Unsubscribed'] = ApiClient.convertToType(data['Unsubscribed'], ['String']);
      }
      if (data.hasOwnProperty('UnsubscribedCount')) {
        obj['UnsubscribedCount'] = ApiClient.convertToType(data['UnsubscribedCount'], 'Number');
      }
      if (data.hasOwnProperty('AbuseReports')) {
        obj['AbuseReports'] = ApiClient.convertToType(data['AbuseReports'], ['String']);
      }
      if (data.hasOwnProperty('AbuseReportsCount')) {
        obj['AbuseReportsCount'] = ApiClient.convertToType(data['AbuseReportsCount'], 'Number');
      }
      if (data.hasOwnProperty('MessageIDs')) {
        obj['MessageIDs'] = ApiClient.convertToType(data['MessageIDs'], ['String']);
      }
    }
    return obj;
  }

  /**
   * ID number of your attachment
   * @member {String} ID
   */
  exports.prototype['ID'] = undefined;
  /**
   * Name of status: submitted, complete, in_progress
   * @member {String} Status
   */
  exports.prototype['Status'] = undefined;
  /**
   * @member {Number} RecipientsCount
   */
  exports.prototype['RecipientsCount'] = undefined;
  /**
   * @member {Array.<module:model/EmailJobFailedStatus>} Failed
   */
  exports.prototype['Failed'] = undefined;
  /**
   * Total emails failed.
   * @member {Number} FailedCount
   */
  exports.prototype['FailedCount'] = undefined;
  /**
   * @member {Array.<String>} Sent
   */
  exports.prototype['Sent'] = undefined;
  /**
   * Total emails sent.
   * @member {Number} SentCount
   */
  exports.prototype['SentCount'] = undefined;
  /**
   * Number of delivered messages
   * @member {Array.<String>} Delivered
   */
  exports.prototype['Delivered'] = undefined;
  /**
   * @member {Number} DeliveredCount
   */
  exports.prototype['DeliveredCount'] = undefined;
  /**
   * @member {Array.<String>} Pending
   */
  exports.prototype['Pending'] = undefined;
  /**
   * @member {Number} PendingCount
   */
  exports.prototype['PendingCount'] = undefined;
  /**
   * Number of opened messages
   * @member {Array.<String>} Opened
   */
  exports.prototype['Opened'] = undefined;
  /**
   * Total emails opened.
   * @member {Number} OpenedCount
   */
  exports.prototype['OpenedCount'] = undefined;
  /**
   * Number of clicked messages
   * @member {Array.<String>} Clicked
   */
  exports.prototype['Clicked'] = undefined;
  /**
   * Total emails clicked
   * @member {Number} ClickedCount
   */
  exports.prototype['ClickedCount'] = undefined;
  /**
   * Number of unsubscribed messages
   * @member {Array.<String>} Unsubscribed
   */
  exports.prototype['Unsubscribed'] = undefined;
  /**
   * Total emails unsubscribed
   * @member {Number} UnsubscribedCount
   */
  exports.prototype['UnsubscribedCount'] = undefined;
  /**
   * @member {Array.<String>} AbuseReports
   */
  exports.prototype['AbuseReports'] = undefined;
  /**
   * @member {Number} AbuseReportsCount
   */
  exports.prototype['AbuseReportsCount'] = undefined;
  /**
   * List of all MessageIDs for this job.
   * @member {Array.<String>} MessageIDs
   */
  exports.prototype['MessageIDs'] = undefined;



  return exports;
}));


