/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.EmailCredits = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EmailCredits model module.
   * @module model/EmailCredits
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>EmailCredits</code>.
   * Detailed information about email credits
   * @alias module:model/EmailCredits
   * @class
   * @param _date {Date} Date in YYYY-MM-DDThh:ii:ss format
   * @param amount {Number} Amount of money in transaction
   * @param source {String} Source of URL of payment
   * @param notes {String} Free form field of notes
   */
  var exports = function(_date, amount, source, notes) {
    var _this = this;

    _this['Date'] = _date;
    _this['Amount'] = amount;
    _this['Source'] = source;
    _this['Notes'] = notes;
  };

  /**
   * Constructs a <code>EmailCredits</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmailCredits} obj Optional instance to populate.
   * @return {module:model/EmailCredits} The populated <code>EmailCredits</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Date')) {
        obj['Date'] = ApiClient.convertToType(data['Date'], 'Date');
      }
      if (data.hasOwnProperty('Amount')) {
        obj['Amount'] = ApiClient.convertToType(data['Amount'], 'Number');
      }
      if (data.hasOwnProperty('Source')) {
        obj['Source'] = ApiClient.convertToType(data['Source'], 'String');
      }
      if (data.hasOwnProperty('Notes')) {
        obj['Notes'] = ApiClient.convertToType(data['Notes'], 'String');
      }
    }
    return obj;
  }

  /**
   * Date in YYYY-MM-DDThh:ii:ss format
   * @member {Date} Date
   */
  exports.prototype['Date'] = undefined;
  /**
   * Amount of money in transaction
   * @member {Number} Amount
   */
  exports.prototype['Amount'] = undefined;
  /**
   * Source of URL of payment
   * @member {String} Source
   */
  exports.prototype['Source'] = undefined;
  /**
   * Free form field of notes
   * @member {String} Notes
   */
  exports.prototype['Notes'] = undefined;



  return exports;
}));


