/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RecipientEvent'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RecipientEvent'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.EventLog = factory(root.ElasticemailRestfulApi.ApiClient, root.ElasticemailRestfulApi.RecipientEvent);
  }
}(this, function(ApiClient, RecipientEvent) {
  'use strict';




  /**
   * The EventLog model module.
   * @module model/EventLog
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>EventLog</code>.
   * Event logs for selected date range
   * @alias module:model/EventLog
   * @class
   * @param recipients {Array.<module:model/RecipientEvent>} Number of recipients
   */
  var exports = function(recipients) {
    var _this = this;



    _this['Recipients'] = recipients;
  };

  /**
   * Constructs a <code>EventLog</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventLog} obj Optional instance to populate.
   * @return {module:model/EventLog} The populated <code>EventLog</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('From')) {
        obj['From'] = ApiClient.convertToType(data['From'], 'Date');
      }
      if (data.hasOwnProperty('To')) {
        obj['To'] = ApiClient.convertToType(data['To'], 'Date');
      }
      if (data.hasOwnProperty('Recipients')) {
        obj['Recipients'] = ApiClient.convertToType(data['Recipients'], [RecipientEvent]);
      }
    }
    return obj;
  }

  /**
   * Starting date for search in YYYY-MM-DDThh:mm:ss format.
   * @member {Date} From
   */
  exports.prototype['From'] = undefined;
  /**
   * Ending date for search in YYYY-MM-DDThh:mm:ss format.
   * @member {Date} To
   */
  exports.prototype['To'] = undefined;
  /**
   * Number of recipients
   * @member {Array.<module:model/RecipientEvent>} Recipients
   */
  exports.prototype['Recipients'] = undefined;



  return exports;
}));


