/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.ExportLink = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExportLink model module.
   * @module model/ExportLink
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>ExportLink</code>.
   * @alias module:model/ExportLink
   * @class
   * @param link {String} Direct URL to the exported file
   * @param publicExportID {String} ID of the exported file
   */
  var exports = function(link, publicExportID) {
    var _this = this;

    _this['Link'] = link;
    _this['PublicExportID'] = publicExportID;
  };

  /**
   * Constructs a <code>ExportLink</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExportLink} obj Optional instance to populate.
   * @return {module:model/ExportLink} The populated <code>ExportLink</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Link')) {
        obj['Link'] = ApiClient.convertToType(data['Link'], 'String');
      }
      if (data.hasOwnProperty('PublicExportID')) {
        obj['PublicExportID'] = ApiClient.convertToType(data['PublicExportID'], 'String');
      }
    }
    return obj;
  }

  /**
   * Direct URL to the exported file
   * @member {String} Link
   */
  exports.prototype['Link'] = undefined;
  /**
   * ID of the exported file
   * @member {String} PublicExportID
   */
  exports.prototype['PublicExportID'] = undefined;



  return exports;
}));


