/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.List = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The List model module.
   * @module model/List
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>List</code>.
   * List of Lists, with detailed data about its contents.
   * @alias module:model/List
   * @class
   * @param listName {String} Name of your list.
   * @param count {Number} Number of items.
   * @param dateAdded {Date} Date of creation in YYYY-MM-DDThh:ii:ss format
   * @param allowUnsubscribe {Boolean} True: Allow unsubscribing from this list. Otherwise, false
   * @param rule {String} Query used for filtering.
   */
  var exports = function(listName, count, dateAdded, allowUnsubscribe, rule) {
    var _this = this;

    _this['ListName'] = listName;
    _this['Count'] = count;

    _this['DateAdded'] = dateAdded;
    _this['AllowUnsubscribe'] = allowUnsubscribe;
    _this['Rule'] = rule;
  };

  /**
   * Constructs a <code>List</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/List} obj Optional instance to populate.
   * @return {module:model/List} The populated <code>List</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ListName')) {
        obj['ListName'] = ApiClient.convertToType(data['ListName'], 'String');
      }
      if (data.hasOwnProperty('Count')) {
        obj['Count'] = ApiClient.convertToType(data['Count'], 'Number');
      }
      if (data.hasOwnProperty('PublicListID')) {
        obj['PublicListID'] = ApiClient.convertToType(data['PublicListID'], 'String');
      }
      if (data.hasOwnProperty('DateAdded')) {
        obj['DateAdded'] = ApiClient.convertToType(data['DateAdded'], 'Date');
      }
      if (data.hasOwnProperty('AllowUnsubscribe')) {
        obj['AllowUnsubscribe'] = ApiClient.convertToType(data['AllowUnsubscribe'], 'Boolean');
      }
      if (data.hasOwnProperty('Rule')) {
        obj['Rule'] = ApiClient.convertToType(data['Rule'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of your list.
   * @member {String} ListName
   */
  exports.prototype['ListName'] = undefined;
  /**
   * Number of items.
   * @member {Number} Count
   */
  exports.prototype['Count'] = undefined;
  /**
   * ID code of list
   * @member {String} PublicListID
   */
  exports.prototype['PublicListID'] = undefined;
  /**
   * Date of creation in YYYY-MM-DDThh:ii:ss format
   * @member {Date} DateAdded
   */
  exports.prototype['DateAdded'] = undefined;
  /**
   * True: Allow unsubscribing from this list. Otherwise, false
   * @member {Boolean} AllowUnsubscribe
   */
  exports.prototype['AllowUnsubscribe'] = undefined;
  /**
   * Query used for filtering.
   * @member {String} Rule
   */
  exports.prototype['Rule'] = undefined;



  return exports;
}));


