/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.ListUpdatePayload = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ListUpdatePayload model module.
   * @module model/ListUpdatePayload
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>ListUpdatePayload</code>.
   * @alias module:model/ListUpdatePayload
   * @class
   * @param newListName {String} Name of your list if you want to change it.
   * @param allowUnsubscribe {Boolean} True: Allow unsubscribing from this list. Otherwise, false
   */
  var exports = function(newListName, allowUnsubscribe) {
    var _this = this;

    _this['NewListName'] = newListName;
    _this['AllowUnsubscribe'] = allowUnsubscribe;
  };

  /**
   * Constructs a <code>ListUpdatePayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListUpdatePayload} obj Optional instance to populate.
   * @return {module:model/ListUpdatePayload} The populated <code>ListUpdatePayload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('NewListName')) {
        obj['NewListName'] = ApiClient.convertToType(data['NewListName'], 'String');
      }
      if (data.hasOwnProperty('AllowUnsubscribe')) {
        obj['AllowUnsubscribe'] = ApiClient.convertToType(data['AllowUnsubscribe'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Name of your list if you want to change it.
   * @member {String} NewListName
   */
  exports.prototype['NewListName'] = undefined;
  /**
   * True: Allow unsubscribing from this list. Otherwise, false
   * @member {Boolean} AllowUnsubscribe
   */
  exports.prototype['AllowUnsubscribe'] = undefined;



  return exports;
}));


