/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.LoginResponse = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LoginResponse model module.
   * @module model/LoginResponse
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>LoginResponse</code>.
   * @alias module:model/LoginResponse
   * @class
   * @param apiKey {String} ApiKey that gives you access to our SMTP and HTTP API's.
   * @param status {module:model/LoginResponse.StatusEnum} Name of status: Active, Engaged, Inactive, Abuse, Bounced, Unsubscribed.
   */
  var exports = function(apiKey, status) {
    var _this = this;

    _this['ApiKey'] = apiKey;

    _this['Status'] = status;
  };

  /**
   * Constructs a <code>LoginResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginResponse} obj Optional instance to populate.
   * @return {module:model/LoginResponse} The populated <code>LoginResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ApiKey')) {
        obj['ApiKey'] = ApiClient.convertToType(data['ApiKey'], 'String');
      }
      if (data.hasOwnProperty('TwoFactorAuthCodeDateCreated')) {
        obj['TwoFactorAuthCodeDateCreated'] = ApiClient.convertToType(data['TwoFactorAuthCodeDateCreated'], 'Date');
      }
      if (data.hasOwnProperty('Status')) {
        obj['Status'] = ApiClient.convertToType(data['Status'], 'String');
      }
    }
    return obj;
  }

  /**
   * ApiKey that gives you access to our SMTP and HTTP API's.
   * @member {String} ApiKey
   */
  exports.prototype['ApiKey'] = undefined;
  /**
   * @member {Date} TwoFactorAuthCodeDateCreated
   */
  exports.prototype['TwoFactorAuthCodeDateCreated'] = undefined;
  /**
   * Name of status: Active, Engaged, Inactive, Abuse, Bounced, Unsubscribed.
   * @member {module:model/LoginResponse.StatusEnum} Status
   */
  exports.prototype['Status'] = undefined;


  /**
   * Allowed values for the <code>Status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "UserOrPasswordIncorrect"
     * @const
     */
    "UserOrPasswordIncorrect": "UserOrPasswordIncorrect",
    /**
     * value: "TwoFactorCodeRequired"
     * @const
     */
    "TwoFactorCodeRequired": "TwoFactorCodeRequired",
    /**
     * value: "TwoFactorCodeExpired"
     * @const
     */
    "TwoFactorCodeExpired": "TwoFactorCodeExpired",
    /**
     * value: "TwoFactorCodeIncorrect"
     * @const
     */
    "TwoFactorCodeIncorrect": "TwoFactorCodeIncorrect",
    /**
     * value: "Success"
     * @const
     */
    "Success": "Success"  };


  return exports;
}));


