/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BouncedCategorySummary', 'model/DailyLogStatusSummary', 'model/LogStatusSummary'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BouncedCategorySummary'), require('./DailyLogStatusSummary'), require('./LogStatusSummary'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.LogSummary = factory(root.ElasticemailRestfulApi.ApiClient, root.ElasticemailRestfulApi.BouncedCategorySummary, root.ElasticemailRestfulApi.DailyLogStatusSummary, root.ElasticemailRestfulApi.LogStatusSummary);
  }
}(this, function(ApiClient, BouncedCategorySummary, DailyLogStatusSummary, LogStatusSummary) {
  'use strict';




  /**
   * The LogSummary model module.
   * @module model/LogSummary
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>LogSummary</code>.
   * Overall log summary information.
   * @alias module:model/LogSummary
   * @class
   * @param logStatusSummary {module:model/LogStatusSummary} 
   * @param bouncedCategorySummary {module:model/BouncedCategorySummary} 
   * @param dailyLogStatusSummary {Array.<module:model/DailyLogStatusSummary>} Daily summary of log status, based on specified date range.
   */
  var exports = function(logStatusSummary, bouncedCategorySummary, dailyLogStatusSummary) {
    var _this = this;

    _this['LogStatusSummary'] = logStatusSummary;
    _this['BouncedCategorySummary'] = bouncedCategorySummary;
    _this['DailyLogStatusSummary'] = dailyLogStatusSummary;
  };

  /**
   * Constructs a <code>LogSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LogSummary} obj Optional instance to populate.
   * @return {module:model/LogSummary} The populated <code>LogSummary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('LogStatusSummary')) {
        obj['LogStatusSummary'] = LogStatusSummary.constructFromObject(data['LogStatusSummary']);
      }
      if (data.hasOwnProperty('BouncedCategorySummary')) {
        obj['BouncedCategorySummary'] = BouncedCategorySummary.constructFromObject(data['BouncedCategorySummary']);
      }
      if (data.hasOwnProperty('DailyLogStatusSummary')) {
        obj['DailyLogStatusSummary'] = ApiClient.convertToType(data['DailyLogStatusSummary'], [DailyLogStatusSummary]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/LogStatusSummary} LogStatusSummary
   */
  exports.prototype['LogStatusSummary'] = undefined;
  /**
   * @member {module:model/BouncedCategorySummary} BouncedCategorySummary
   */
  exports.prototype['BouncedCategorySummary'] = undefined;
  /**
   * Daily summary of log status, based on specified date range.
   * @member {Array.<module:model/DailyLogStatusSummary>} DailyLogStatusSummary
   */
  exports.prototype['DailyLogStatusSummary'] = undefined;



  return exports;
}));


