/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.RandomListPayload = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RandomListPayload model module.
   * @module model/RandomListPayload
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>RandomListPayload</code>.
   * @alias module:model/RandomListPayload
   * @class
   * @param listName {String} Name of your list.
   * @param count {Number} Number of items.
   * @param excludeBlocked {Boolean} True if you want to exclude contacts that are currently in a blocked status of either unsubscribe, complaint or bounce. Otherwise, false.
   * @param allowUnsubscribe {Boolean} True: Allow unsubscribing from this list. Otherwise, false
   * @param rule {String} Query used for filtering.
   * @param allContacts {Boolean} True: Include every Contact in your Account. Otherwise, false
   */
  var exports = function(listName, count, excludeBlocked, allowUnsubscribe, rule, allContacts) {
    var _this = this;

    _this['ListName'] = listName;
    _this['Count'] = count;
    _this['ExcludeBlocked'] = excludeBlocked;
    _this['AllowUnsubscribe'] = allowUnsubscribe;
    _this['Rule'] = rule;
    _this['AllContacts'] = allContacts;
  };

  /**
   * Constructs a <code>RandomListPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RandomListPayload} obj Optional instance to populate.
   * @return {module:model/RandomListPayload} The populated <code>RandomListPayload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ListName')) {
        obj['ListName'] = ApiClient.convertToType(data['ListName'], 'String');
      }
      if (data.hasOwnProperty('Count')) {
        obj['Count'] = ApiClient.convertToType(data['Count'], 'Number');
      }
      if (data.hasOwnProperty('ExcludeBlocked')) {
        obj['ExcludeBlocked'] = ApiClient.convertToType(data['ExcludeBlocked'], 'Boolean');
      }
      if (data.hasOwnProperty('AllowUnsubscribe')) {
        obj['AllowUnsubscribe'] = ApiClient.convertToType(data['AllowUnsubscribe'], 'Boolean');
      }
      if (data.hasOwnProperty('Rule')) {
        obj['Rule'] = ApiClient.convertToType(data['Rule'], 'String');
      }
      if (data.hasOwnProperty('AllContacts')) {
        obj['AllContacts'] = ApiClient.convertToType(data['AllContacts'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Name of your list.
   * @member {String} ListName
   */
  exports.prototype['ListName'] = undefined;
  /**
   * Number of items.
   * @member {Number} Count
   */
  exports.prototype['Count'] = undefined;
  /**
   * True if you want to exclude contacts that are currently in a blocked status of either unsubscribe, complaint or bounce. Otherwise, false.
   * @member {Boolean} ExcludeBlocked
   */
  exports.prototype['ExcludeBlocked'] = undefined;
  /**
   * True: Allow unsubscribing from this list. Otherwise, false
   * @member {Boolean} AllowUnsubscribe
   */
  exports.prototype['AllowUnsubscribe'] = undefined;
  /**
   * Query used for filtering.
   * @member {String} Rule
   */
  exports.prototype['Rule'] = undefined;
  /**
   * True: Include every Contact in your Account. Otherwise, false
   * @member {Boolean} AllContacts
   */
  exports.prototype['AllContacts'] = undefined;



  return exports;
}));


