/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.RecipientEvent = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RecipientEvent model module.
   * @module model/RecipientEvent
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>RecipientEvent</code>.
   * Detailed information about message recipient
   * @alias module:model/RecipientEvent
   * @class
   * @param jobID {String} ID of certain mail job
   * @param msgID {String} ID number of selected message.
   * @param fromEmail {String} Default From: email address.
   * @param to {String} Ending date for search in YYYY-MM-DDThh:mm:ss format.
   * @param subject {String} Default subject of email.
   * @param eventType {String} Name of recipient's status: Submitted, ReadyToSend, WaitingToRetry, Sending, Bounced, Sent, Opened, Clicked, Unsubscribed, AbuseReport
   * @param eventDate {String} Creation date
   * @param channel {String} Name of selected Channel.
   * @param messageCategory {String} Name of message category
   * @param nextTryOn {String} Date of next try
   */
  var exports = function(jobID, msgID, fromEmail, to, subject, eventType, eventDate, channel, messageCategory, nextTryOn) {
    var _this = this;

    _this['JobID'] = jobID;
    _this['MsgID'] = msgID;
    _this['FromEmail'] = fromEmail;
    _this['To'] = to;
    _this['Subject'] = subject;
    _this['EventType'] = eventType;
    _this['EventDate'] = eventDate;
    _this['Channel'] = channel;
    _this['MessageCategory'] = messageCategory;
    _this['NextTryOn'] = nextTryOn;
  };

  /**
   * Constructs a <code>RecipientEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecipientEvent} obj Optional instance to populate.
   * @return {module:model/RecipientEvent} The populated <code>RecipientEvent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('JobID')) {
        obj['JobID'] = ApiClient.convertToType(data['JobID'], 'String');
      }
      if (data.hasOwnProperty('MsgID')) {
        obj['MsgID'] = ApiClient.convertToType(data['MsgID'], 'String');
      }
      if (data.hasOwnProperty('FromEmail')) {
        obj['FromEmail'] = ApiClient.convertToType(data['FromEmail'], 'String');
      }
      if (data.hasOwnProperty('To')) {
        obj['To'] = ApiClient.convertToType(data['To'], 'String');
      }
      if (data.hasOwnProperty('Subject')) {
        obj['Subject'] = ApiClient.convertToType(data['Subject'], 'String');
      }
      if (data.hasOwnProperty('EventType')) {
        obj['EventType'] = ApiClient.convertToType(data['EventType'], 'String');
      }
      if (data.hasOwnProperty('EventDate')) {
        obj['EventDate'] = ApiClient.convertToType(data['EventDate'], 'String');
      }
      if (data.hasOwnProperty('Channel')) {
        obj['Channel'] = ApiClient.convertToType(data['Channel'], 'String');
      }
      if (data.hasOwnProperty('MessageCategory')) {
        obj['MessageCategory'] = ApiClient.convertToType(data['MessageCategory'], 'String');
      }
      if (data.hasOwnProperty('NextTryOn')) {
        obj['NextTryOn'] = ApiClient.convertToType(data['NextTryOn'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID of certain mail job
   * @member {String} JobID
   */
  exports.prototype['JobID'] = undefined;
  /**
   * ID number of selected message.
   * @member {String} MsgID
   */
  exports.prototype['MsgID'] = undefined;
  /**
   * Default From: email address.
   * @member {String} FromEmail
   */
  exports.prototype['FromEmail'] = undefined;
  /**
   * Ending date for search in YYYY-MM-DDThh:mm:ss format.
   * @member {String} To
   */
  exports.prototype['To'] = undefined;
  /**
   * Default subject of email.
   * @member {String} Subject
   */
  exports.prototype['Subject'] = undefined;
  /**
   * Name of recipient's status: Submitted, ReadyToSend, WaitingToRetry, Sending, Bounced, Sent, Opened, Clicked, Unsubscribed, AbuseReport
   * @member {String} EventType
   */
  exports.prototype['EventType'] = undefined;
  /**
   * Creation date
   * @member {String} EventDate
   */
  exports.prototype['EventDate'] = undefined;
  /**
   * Name of selected Channel.
   * @member {String} Channel
   */
  exports.prototype['Channel'] = undefined;
  /**
   * Name of message category
   * @member {String} MessageCategory
   */
  exports.prototype['MessageCategory'] = undefined;
  /**
   * Date of next try
   * @member {String} NextTryOn
   */
  exports.prototype['NextTryOn'] = undefined;



  return exports;
}));


