/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.Referral = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Referral model module.
   * @module model/Referral
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>Referral</code>.
   * Referral details for this account.
   * @alias module:model/Referral
   * @class
   * @param currentReferralCredit {Number} Current amount of dolars you have from referring.
   * @param currentReferralCount {Number} Number of active referrals.
   */
  var exports = function(currentReferralCredit, currentReferralCount) {
    var _this = this;

    _this['CurrentReferralCredit'] = currentReferralCredit;
    _this['CurrentReferralCount'] = currentReferralCount;
  };

  /**
   * Constructs a <code>Referral</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Referral} obj Optional instance to populate.
   * @return {module:model/Referral} The populated <code>Referral</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('CurrentReferralCredit')) {
        obj['CurrentReferralCredit'] = ApiClient.convertToType(data['CurrentReferralCredit'], 'Number');
      }
      if (data.hasOwnProperty('CurrentReferralCount')) {
        obj['CurrentReferralCount'] = ApiClient.convertToType(data['CurrentReferralCount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Current amount of dolars you have from referring.
   * @member {Number} CurrentReferralCredit
   */
  exports.prototype['CurrentReferralCredit'] = undefined;
  /**
   * Number of active referrals.
   * @member {Number} CurrentReferralCount
   */
  exports.prototype['CurrentReferralCount'] = undefined;



  return exports;
}));


