/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.SpamRule = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SpamRule model module.
   * @module model/SpamRule
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>SpamRule</code>.
   * Single spam score
   * @alias module:model/SpamRule
   * @class
   * @param score {String} Spam score
   * @param key {String} Name of rule
   * @param description {String} Description of rule.
   */
  var exports = function(score, key, description) {
    var _this = this;

    _this['Score'] = score;
    _this['Key'] = key;
    _this['Description'] = description;
  };

  /**
   * Constructs a <code>SpamRule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SpamRule} obj Optional instance to populate.
   * @return {module:model/SpamRule} The populated <code>SpamRule</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Score')) {
        obj['Score'] = ApiClient.convertToType(data['Score'], 'String');
      }
      if (data.hasOwnProperty('Key')) {
        obj['Key'] = ApiClient.convertToType(data['Key'], 'String');
      }
      if (data.hasOwnProperty('Description')) {
        obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
      }
    }
    return obj;
  }

  /**
   * Spam score
   * @member {String} Score
   */
  exports.prototype['Score'] = undefined;
  /**
   * Name of rule
   * @member {String} Key
   */
  exports.prototype['Key'] = undefined;
  /**
   * Description of rule.
   * @member {String} Description
   */
  exports.prototype['Description'] = undefined;



  return exports;
}));


