/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.SplitOptions = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SplitOptions model module.
   * @module model/SplitOptions
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>SplitOptions</code>.
   * @alias module:model/SplitOptions
   * @class
   * @param splitOptimization {module:model/SplitOptions.SplitOptimizationEnum} What should be checked for choosing the winner: opens or clicks
   * @param determineWinnerAfterXMinutes {Number} 
   */
  var exports = function(splitOptimization, determineWinnerAfterXMinutes) {
    var _this = this;

    _this['SplitOptimization'] = splitOptimization;
    _this['DetermineWinnerAfterXMinutes'] = determineWinnerAfterXMinutes;
  };

  /**
   * Constructs a <code>SplitOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SplitOptions} obj Optional instance to populate.
   * @return {module:model/SplitOptions} The populated <code>SplitOptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('SplitOptimization')) {
        obj['SplitOptimization'] = ApiClient.convertToType(data['SplitOptimization'], 'String');
      }
      if (data.hasOwnProperty('DetermineWinnerAfterXMinutes')) {
        obj['DetermineWinnerAfterXMinutes'] = ApiClient.convertToType(data['DetermineWinnerAfterXMinutes'], 'Number');
      }
    }
    return obj;
  }

  /**
   * What should be checked for choosing the winner: opens or clicks
   * @member {module:model/SplitOptions.SplitOptimizationEnum} SplitOptimization
   */
  exports.prototype['SplitOptimization'] = undefined;
  /**
   * @member {Number} DetermineWinnerAfterXMinutes
   */
  exports.prototype['DetermineWinnerAfterXMinutes'] = undefined;


  /**
   * Allowed values for the <code>SplitOptimization</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SplitOptimizationEnum = {
    /**
     * value: "Opened"
     * @const
     */
    "Opened": "Opened",
    /**
     * value: "Clicked"
     * @const
     */
    "Clicked": "Clicked"  };


  return exports;
}));


