/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.SubaccountCreditsPayload = factory(root.ElasticemailRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SubaccountCreditsPayload model module.
   * @module model/SubaccountCreditsPayload
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>SubaccountCreditsPayload</code>.
   * 
   * @alias module:model/SubaccountCreditsPayload
   * @class
   * @param credits {Number} 
   * @param notes {String} Free form field of notes
   */
  var exports = function(credits, notes) {
    var _this = this;

    _this['Credits'] = credits;
    _this['Notes'] = notes;
  };

  /**
   * Constructs a <code>SubaccountCreditsPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubaccountCreditsPayload} obj Optional instance to populate.
   * @return {module:model/SubaccountCreditsPayload} The populated <code>SubaccountCreditsPayload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Credits')) {
        obj['Credits'] = ApiClient.convertToType(data['Credits'], 'Number');
      }
      if (data.hasOwnProperty('Notes')) {
        obj['Notes'] = ApiClient.convertToType(data['Notes'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} Credits
   */
  exports.prototype['Credits'] = undefined;
  /**
   * Free form field of notes
   * @member {String} Notes
   */
  exports.prototype['Notes'] = undefined;



  return exports;
}));


