/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TriggerData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TriggerData'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.TriggerOptions = factory(root.ElasticemailRestfulApi.ApiClient, root.ElasticemailRestfulApi.TriggerData);
  }
}(this, function(ApiClient, TriggerData) {
  'use strict';




  /**
   * The TriggerOptions model module.
   * @module model/TriggerOptions
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>TriggerOptions</code>.
   * 
   * @alias module:model/TriggerOptions
   * @class
   * @param type {module:model/TriggerOptions.TypeEnum} 
   * @param sendAfterXMinutes {Number} 
   * @param sendEveryXMinutes {Number} 
   * @param sendXTimes {Number} 
   * @param triggeredBy {module:model/TriggerData} 
   */
  var exports = function(type, sendAfterXMinutes, sendEveryXMinutes, sendXTimes, triggeredBy) {
    var _this = this;

    _this['Type'] = type;

    _this['SendAfterXMinutes'] = sendAfterXMinutes;
    _this['SendEveryXMinutes'] = sendEveryXMinutes;
    _this['SendXTimes'] = sendXTimes;
    _this['TriggeredBy'] = triggeredBy;
  };

  /**
   * Constructs a <code>TriggerOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TriggerOptions} obj Optional instance to populate.
   * @return {module:model/TriggerOptions} The populated <code>TriggerOptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Type')) {
        obj['Type'] = ApiClient.convertToType(data['Type'], 'String');
      }
      if (data.hasOwnProperty('DateToSendOn')) {
        obj['DateToSendOn'] = ApiClient.convertToType(data['DateToSendOn'], 'Date');
      }
      if (data.hasOwnProperty('SendAfterXMinutes')) {
        obj['SendAfterXMinutes'] = ApiClient.convertToType(data['SendAfterXMinutes'], 'Number');
      }
      if (data.hasOwnProperty('SendEveryXMinutes')) {
        obj['SendEveryXMinutes'] = ApiClient.convertToType(data['SendEveryXMinutes'], 'Number');
      }
      if (data.hasOwnProperty('SendXTimes')) {
        obj['SendXTimes'] = ApiClient.convertToType(data['SendXTimes'], 'Number');
      }
      if (data.hasOwnProperty('TriggeredBy')) {
        obj['TriggeredBy'] = TriggerData.constructFromObject(data['TriggeredBy']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/TriggerOptions.TypeEnum} Type
   */
  exports.prototype['Type'] = undefined;
  /**
   * @member {Date} DateToSendOn
   */
  exports.prototype['DateToSendOn'] = undefined;
  /**
   * @member {Number} SendAfterXMinutes
   */
  exports.prototype['SendAfterXMinutes'] = undefined;
  /**
   * @member {Number} SendEveryXMinutes
   */
  exports.prototype['SendEveryXMinutes'] = undefined;
  /**
   * @member {Number} SendXTimes
   */
  exports.prototype['SendXTimes'] = undefined;
  /**
   * @member {module:model/TriggerData} TriggeredBy
   */
  exports.prototype['TriggeredBy'] = undefined;


  /**
   * Allowed values for the <code>Type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "SendNow"
     * @const
     */
    "SendNow": "SendNow",
    /**
     * value: "FutureScheduled"
     * @const
     */
    "FutureScheduled": "FutureScheduled",
    /**
     * value: "OnAdd"
     * @const
     */
    "OnAdd": "OnAdd",
    /**
     * value: "OnOpen"
     * @const
     */
    "OnOpen": "OnOpen",
    /**
     * value: "OnClick"
     * @const
     */
    "OnClick": "OnClick"  };


  return exports;
}));


