/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DomainDetail', 'model/DomainPayload'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DomainDetail'), require('../model/DomainPayload'));
  } else {
    // Browser globals (root is window)
    if (!root.ElasticemailRestfulApi) {
      root.ElasticemailRestfulApi = {};
    }
    root.ElasticemailRestfulApi.DomainsApi = factory(root.ElasticemailRestfulApi.ApiClient, root.ElasticemailRestfulApi.DomainDetail, root.ElasticemailRestfulApi.DomainPayload);
  }
}(this, function(ApiClient, DomainDetail, DomainPayload) {
  'use strict';

  /**
   * Domains service.
   * @module api/DomainsApi
   * @version 3.0.0b
   */

  /**
   * Constructs a new DomainsApi. 
   * @alias module:api/DomainsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the domainsDomainDelete operation.
     * @callback module:api/DomainsApi~domainsDomainDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes configured domain from account
     * @param {String} domain Name of the given domain
     * @param {module:api/DomainsApi~domainsDomainDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainDelete = function(domain, callback) {
      var postBody = null;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainDelete");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainGet operation.
     * @callback module:api/DomainsApi~domainsDomainGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DomainDetail} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve a domain configured for this account.
     * @param {String} domain Name of the given domain
     * @param {module:api/DomainsApi~domainsDomainGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DomainDetail}
     */
    this.domainsDomainGet = function(domain, callback) {
      var postBody = null;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainGet");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = DomainDetail;

      return this.apiClient.callApi(
        '/domains/{domain}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainPut operation.
     * @callback module:api/DomainsApi~domainsDomainPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DomainDetail} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the selected Domain
     * @param {String} domain Name of the given domain
     * @param {module:model/DomainDetail} body Updated Domain resource
     * @param {module:api/DomainsApi~domainsDomainPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DomainDetail}
     */
    this.domainsDomainPut = function(domain, body, callback) {
      var postBody = body;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainPut");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling domainsDomainPut");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = DomainDetail;

      return this.apiClient.callApi(
        '/domains/{domain}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainVerificationPut operation.
     * @callback module:api/DomainsApi~domainsDomainVerificationPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DomainDetail} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Verification of domain records
     * @param {String} domain Name of the given domain
     * @param {Object} opts Optional parameters
     * @param {String} opts.body Tracking type used in the Tracking verification
     * @param {module:api/DomainsApi~domainsDomainVerificationPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DomainDetail}
     */
    this.domainsDomainVerificationPut = function(domain, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainVerificationPut");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = DomainDetail;

      return this.apiClient.callApi(
        '/domains/{domain}/verification', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsGet operation.
     * @callback module:api/DomainsApi~domainsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DomainDetail>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lists all domains configured for this account.
     * @param {module:api/DomainsApi~domainsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DomainDetail>}
     */
    this.domainsGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [DomainDetail];

      return this.apiClient.callApi(
        '/domains', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsPost operation.
     * @callback module:api/DomainsApi~domainsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DomainDetail} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add new domain to account
     * @param {module:model/DomainPayload} body Domain to add
     * @param {module:api/DomainsApi~domainsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DomainDetail}
     */
    this.domainsPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling domainsPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = DomainDetail;

      return this.apiClient.callApi(
        '/domains', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
