/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticemailRestfulApi);
  }
}(this, function(expect, ElasticemailRestfulApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContactUnsubscribeReasonCounts', function() {
    it('should create an instance of ContactUnsubscribeReasonCounts', function() {
      // uncomment below and update the code to test ContactUnsubscribeReasonCounts
      //var instane = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
      //expect(instance).to.be.a(ElasticemailRestfulApi.ContactUnsubscribeReasonCounts);
    });

    it('should have the property unknown (base name: "Unknown")', function() {
      // uncomment below and update the code to test the property unknown
      //var instane = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
      //expect(instance).to.be();
    });

    it('should have the property noLongerWant (base name: "NoLongerWant")', function() {
      // uncomment below and update the code to test the property noLongerWant
      //var instane = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
      //expect(instance).to.be();
    });

    it('should have the property irrelevantContent (base name: "IrrelevantContent")', function() {
      // uncomment below and update the code to test the property irrelevantContent
      //var instane = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
      //expect(instance).to.be();
    });

    it('should have the property tooFrequent (base name: "TooFrequent")', function() {
      // uncomment below and update the code to test the property tooFrequent
      //var instane = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
      //expect(instance).to.be();
    });

    it('should have the property neverConsented (base name: "NeverConsented")', function() {
      // uncomment below and update the code to test the property neverConsented
      //var instane = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
      //expect(instance).to.be();
    });

    it('should have the property deceptiveContent (base name: "DeceptiveContent")', function() {
      // uncomment below and update the code to test the property deceptiveContent
      //var instane = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
      //expect(instance).to.be();
    });

    it('should have the property abuseReported (base name: "AbuseReported")', function() {
      // uncomment below and update the code to test the property abuseReported
      //var instane = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
      //expect(instance).to.be();
    });

    it('should have the property thirdParty (base name: "ThirdParty")', function() {
      // uncomment below and update the code to test the property thirdParty
      //var instane = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
      //expect(instance).to.be();
    });

    it('should have the property listUnsubscribe (base name: "ListUnsubscribe")', function() {
      // uncomment below and update the code to test the property listUnsubscribe
      //var instane = new ElasticemailRestfulApi.ContactUnsubscribeReasonCounts();
      //expect(instance).to.be();
    });

  });

}));
