/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticemailRestfulApi);
  }
}(this, function(expect, ElasticemailRestfulApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticemailRestfulApi.DomainDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DomainDetail', function() {
    it('should create an instance of DomainDetail', function() {
      // uncomment below and update the code to test DomainDetail
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be.a(ElasticemailRestfulApi.DomainDetail);
    });

    it('should have the property domain (base name: "Domain")', function() {
      // uncomment below and update the code to test the property domain
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property defaultDomain (base name: "DefaultDomain")', function() {
      // uncomment below and update the code to test the property defaultDomain
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property spf (base name: "Spf")', function() {
      // uncomment below and update the code to test the property spf
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property dkim (base name: "Dkim")', function() {
      // uncomment below and update the code to test the property dkim
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property MX (base name: "MX")', function() {
      // uncomment below and update the code to test the property MX
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property DMARC (base name: "DMARC")', function() {
      // uncomment below and update the code to test the property DMARC
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property isRewriteDomainValid (base name: "IsRewriteDomainValid")', function() {
      // uncomment below and update the code to test the property isRewriteDomainValid
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property verify (base name: "Verify")', function() {
      // uncomment below and update the code to test the property verify
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "Type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property trackingStatus (base name: "TrackingStatus")', function() {
      // uncomment below and update the code to test the property trackingStatus
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property certificateStatus (base name: "CertificateStatus")', function() {
      // uncomment below and update the code to test the property certificateStatus
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property certificateValidationError (base name: "CertificateValidationError")', function() {
      // uncomment below and update the code to test the property certificateValidationError
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

    it('should have the property trackingTypeUserRequest (base name: "TrackingTypeUserRequest")', function() {
      // uncomment below and update the code to test the property trackingTypeUserRequest
      //var instane = new ElasticemailRestfulApi.DomainDetail();
      //expect(instance).to.be();
    });

  });

}));
