/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticemailRestfulApi);
  }
}(this, function(expect, ElasticemailRestfulApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticemailRestfulApi.EmailJobStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmailJobStatus', function() {
    it('should create an instance of EmailJobStatus', function() {
      // uncomment below and update the code to test EmailJobStatus
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be.a(ElasticemailRestfulApi.EmailJobStatus);
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "Status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property recipientsCount (base name: "RecipientsCount")', function() {
      // uncomment below and update the code to test the property recipientsCount
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property failed (base name: "Failed")', function() {
      // uncomment below and update the code to test the property failed
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property failedCount (base name: "FailedCount")', function() {
      // uncomment below and update the code to test the property failedCount
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property sent (base name: "Sent")', function() {
      // uncomment below and update the code to test the property sent
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property sentCount (base name: "SentCount")', function() {
      // uncomment below and update the code to test the property sentCount
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property delivered (base name: "Delivered")', function() {
      // uncomment below and update the code to test the property delivered
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property deliveredCount (base name: "DeliveredCount")', function() {
      // uncomment below and update the code to test the property deliveredCount
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property pending (base name: "Pending")', function() {
      // uncomment below and update the code to test the property pending
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property pendingCount (base name: "PendingCount")', function() {
      // uncomment below and update the code to test the property pendingCount
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property opened (base name: "Opened")', function() {
      // uncomment below and update the code to test the property opened
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property openedCount (base name: "OpenedCount")', function() {
      // uncomment below and update the code to test the property openedCount
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property clicked (base name: "Clicked")', function() {
      // uncomment below and update the code to test the property clicked
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property clickedCount (base name: "ClickedCount")', function() {
      // uncomment below and update the code to test the property clickedCount
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property unsubscribed (base name: "Unsubscribed")', function() {
      // uncomment below and update the code to test the property unsubscribed
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property unsubscribedCount (base name: "UnsubscribedCount")', function() {
      // uncomment below and update the code to test the property unsubscribedCount
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property abuseReports (base name: "AbuseReports")', function() {
      // uncomment below and update the code to test the property abuseReports
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property abuseReportsCount (base name: "AbuseReportsCount")', function() {
      // uncomment below and update the code to test the property abuseReportsCount
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property messageIDs (base name: "MessageIDs")', function() {
      // uncomment below and update the code to test the property messageIDs
      //var instane = new ElasticemailRestfulApi.EmailJobStatus();
      //expect(instance).to.be();
    });

  });

}));
