/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticemailRestfulApi);
  }
}(this, function(expect, ElasticemailRestfulApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticemailRestfulApi.QuickAddPayload();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QuickAddPayload', function() {
    it('should create an instance of QuickAddPayload', function() {
      // uncomment below and update the code to test QuickAddPayload
      //var instane = new ElasticemailRestfulApi.QuickAddPayload();
      //expect(instance).to.be.a(ElasticemailRestfulApi.QuickAddPayload);
    });

    it('should have the property contacts (base name: "Contacts")', function() {
      // uncomment below and update the code to test the property contacts
      //var instane = new ElasticemailRestfulApi.QuickAddPayload();
      //expect(instance).to.be();
    });

    it('should have the property listName (base name: "ListName")', function() {
      // uncomment below and update the code to test the property listName
      //var instane = new ElasticemailRestfulApi.QuickAddPayload();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "Status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ElasticemailRestfulApi.QuickAddPayload();
      //expect(instance).to.be();
    });

    it('should have the property notifyEmail (base name: "NotifyEmail")', function() {
      // uncomment below and update the code to test the property notifyEmail
      //var instane = new ElasticemailRestfulApi.QuickAddPayload();
      //expect(instance).to.be();
    });

    it('should have the property consentDate (base name: "ConsentDate")', function() {
      // uncomment below and update the code to test the property consentDate
      //var instane = new ElasticemailRestfulApi.QuickAddPayload();
      //expect(instance).to.be();
    });

    it('should have the property consentIP (base name: "ConsentIP")', function() {
      // uncomment below and update the code to test the property consentIP
      //var instane = new ElasticemailRestfulApi.QuickAddPayload();
      //expect(instance).to.be();
    });

    it('should have the property consentTracking (base name: "ConsentTracking")', function() {
      // uncomment below and update the code to test the property consentTracking
      //var instane = new ElasticemailRestfulApi.QuickAddPayload();
      //expect(instance).to.be();
    });

  });

}));
