/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticemailRestfulApi);
  }
}(this, function(expect, ElasticemailRestfulApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticemailRestfulApi.Recipient();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Recipient', function() {
    it('should create an instance of Recipient', function() {
      // uncomment below and update the code to test Recipient
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be.a(ElasticemailRestfulApi.Recipient);
    });

    it('should have the property isSms (base name: "IsSms")', function() {
      // uncomment below and update the code to test the property isSms
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property msgID (base name: "MsgID")', function() {
      // uncomment below and update the code to test the property msgID
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "To")', function() {
      // uncomment below and update the code to test the property to
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "Status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property channel (base name: "Channel")', function() {
      // uncomment below and update the code to test the property channel
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "Date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property dateSent (base name: "DateSent")', function() {
      // uncomment below and update the code to test the property dateSent
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property dateOpened (base name: "DateOpened")', function() {
      // uncomment below and update the code to test the property dateOpened
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property dateClicked (base name: "DateClicked")', function() {
      // uncomment below and update the code to test the property dateClicked
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "Message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property showCategory (base name: "ShowCategory")', function() {
      // uncomment below and update the code to test the property showCategory
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property messageCategory (base name: "MessageCategory")', function() {
      // uncomment below and update the code to test the property messageCategory
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property messageCategoryID (base name: "MessageCategoryID")', function() {
      // uncomment below and update the code to test the property messageCategoryID
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property statusChangeDate (base name: "StatusChangeDate")', function() {
      // uncomment below and update the code to test the property statusChangeDate
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property nextTryOn (base name: "NextTryOn")', function() {
      // uncomment below and update the code to test the property nextTryOn
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "Subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property fromEmail (base name: "FromEmail")', function() {
      // uncomment below and update the code to test the property fromEmail
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property envelopeFrom (base name: "EnvelopeFrom")', function() {
      // uncomment below and update the code to test the property envelopeFrom
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property jobID (base name: "JobID")', function() {
      // uncomment below and update the code to test the property jobID
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property smsUpdateRequired (base name: "SmsUpdateRequired")', function() {
      // uncomment below and update the code to test the property smsUpdateRequired
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property textMessage (base name: "TextMessage")', function() {
      // uncomment below and update the code to test the property textMessage
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property messageSid (base name: "MessageSid")', function() {
      // uncomment below and update the code to test the property messageSid
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property contactLastError (base name: "ContactLastError")', function() {
      // uncomment below and update the code to test the property contactLastError
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property iPAddress (base name: "IPAddress")', function() {
      // uncomment below and update the code to test the property iPAddress
      //var instane = new ElasticemailRestfulApi.Recipient();
      //expect(instance).to.be();
    });

  });

}));
