/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticemailRestfulApi);
  }
}(this, function(expect, ElasticemailRestfulApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticemailRestfulApi.ReputationImpact();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReputationImpact', function() {
    it('should create an instance of ReputationImpact', function() {
      // uncomment below and update the code to test ReputationImpact
      //var instane = new ElasticemailRestfulApi.ReputationImpact();
      //expect(instance).to.be.a(ElasticemailRestfulApi.ReputationImpact);
    });

    it('should have the property abuse (base name: "Abuse")', function() {
      // uncomment below and update the code to test the property abuse
      //var instane = new ElasticemailRestfulApi.ReputationImpact();
      //expect(instance).to.be();
    });

    it('should have the property unknownUsers (base name: "UnknownUsers")', function() {
      // uncomment below and update the code to test the property unknownUsers
      //var instane = new ElasticemailRestfulApi.ReputationImpact();
      //expect(instance).to.be();
    });

    it('should have the property opened (base name: "Opened")', function() {
      // uncomment below and update the code to test the property opened
      //var instane = new ElasticemailRestfulApi.ReputationImpact();
      //expect(instance).to.be();
    });

    it('should have the property clicked (base name: "Clicked")', function() {
      // uncomment below and update the code to test the property clicked
      //var instane = new ElasticemailRestfulApi.ReputationImpact();
      //expect(instance).to.be();
    });

    it('should have the property averageSpamScore (base name: "AverageSpamScore")', function() {
      // uncomment below and update the code to test the property averageSpamScore
      //var instane = new ElasticemailRestfulApi.ReputationImpact();
      //expect(instance).to.be();
    });

    it('should have the property serverFilter (base name: "ServerFilter")', function() {
      // uncomment below and update the code to test the property serverFilter
      //var instane = new ElasticemailRestfulApi.ReputationImpact();
      //expect(instance).to.be();
    });

    it('should have the property trackingDomain (base name: "TrackingDomain")', function() {
      // uncomment below and update the code to test the property trackingDomain
      //var instane = new ElasticemailRestfulApi.ReputationImpact();
      //expect(instance).to.be();
    });

    it('should have the property senderDomain (base name: "SenderDomain")', function() {
      // uncomment below and update the code to test the property senderDomain
      //var instane = new ElasticemailRestfulApi.ReputationImpact();
      //expect(instance).to.be();
    });

  });

}));
