/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticemailRestfulApi);
  }
}(this, function(expect, ElasticemailRestfulApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticemailRestfulApi.CampaignsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CampaignsApi', function() {
    describe('campaignsAbsplitGet', function() {
      it('should call campaignsAbsplitGet successfully', function(done) {
        //uncomment below and update the code to test campaignsAbsplitGet
        //instance.campaignsAbsplitGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsAbsplitNameDelete', function() {
      it('should call campaignsAbsplitNameDelete successfully', function(done) {
        //uncomment below and update the code to test campaignsAbsplitNameDelete
        //instance.campaignsAbsplitNameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsAbsplitNameGet', function() {
      it('should call campaignsAbsplitNameGet successfully', function(done) {
        //uncomment below and update the code to test campaignsAbsplitNameGet
        //instance.campaignsAbsplitNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsAbsplitNamePut', function() {
      it('should call campaignsAbsplitNamePut successfully', function(done) {
        //uncomment below and update the code to test campaignsAbsplitNamePut
        //instance.campaignsAbsplitNamePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsAbsplitPost', function() {
      it('should call campaignsAbsplitPost successfully', function(done) {
        //uncomment below and update the code to test campaignsAbsplitPost
        //instance.campaignsAbsplitPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsAllGet', function() {
      it('should call campaignsAllGet successfully', function(done) {
        //uncomment below and update the code to test campaignsAllGet
        //instance.campaignsAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsAutomatedGet', function() {
      it('should call campaignsAutomatedGet successfully', function(done) {
        //uncomment below and update the code to test campaignsAutomatedGet
        //instance.campaignsAutomatedGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsAutomatedNameDelete', function() {
      it('should call campaignsAutomatedNameDelete successfully', function(done) {
        //uncomment below and update the code to test campaignsAutomatedNameDelete
        //instance.campaignsAutomatedNameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsAutomatedNameGet', function() {
      it('should call campaignsAutomatedNameGet successfully', function(done) {
        //uncomment below and update the code to test campaignsAutomatedNameGet
        //instance.campaignsAutomatedNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsAutomatedNamePut', function() {
      it('should call campaignsAutomatedNamePut successfully', function(done) {
        //uncomment below and update the code to test campaignsAutomatedNamePut
        //instance.campaignsAutomatedNamePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsAutomatedPost', function() {
      it('should call campaignsAutomatedPost successfully', function(done) {
        //uncomment below and update the code to test campaignsAutomatedPost
        //instance.campaignsAutomatedPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsNameCancelPost', function() {
      it('should call campaignsNameCancelPost successfully', function(done) {
        //uncomment below and update the code to test campaignsNameCancelPost
        //instance.campaignsNameCancelPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsSendnowGet', function() {
      it('should call campaignsSendnowGet successfully', function(done) {
        //uncomment below and update the code to test campaignsSendnowGet
        //instance.campaignsSendnowGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsSendnowNameDelete', function() {
      it('should call campaignsSendnowNameDelete successfully', function(done) {
        //uncomment below and update the code to test campaignsSendnowNameDelete
        //instance.campaignsSendnowNameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsSendnowNameGet', function() {
      it('should call campaignsSendnowNameGet successfully', function(done) {
        //uncomment below and update the code to test campaignsSendnowNameGet
        //instance.campaignsSendnowNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsSendnowNamePut', function() {
      it('should call campaignsSendnowNamePut successfully', function(done) {
        //uncomment below and update the code to test campaignsSendnowNamePut
        //instance.campaignsSendnowNamePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsSendnowPost', function() {
      it('should call campaignsSendnowPost successfully', function(done) {
        //uncomment below and update the code to test campaignsSendnowPost
        //instance.campaignsSendnowPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsTasksExportGet', function() {
      it('should call campaignsTasksExportGet successfully', function(done) {
        //uncomment below and update the code to test campaignsTasksExportGet
        //instance.campaignsTasksExportGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
