/**
 * elasticemail_Restful_api
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0b
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticemailRestfulApi);
  }
}(this, function(expect, ElasticemailRestfulApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticemailRestfulApi.ReportsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReportsApi', function() {
    describe('reportsBouncedGet', function() {
      it('should call reportsBouncedGet successfully', function(done) {
        //uncomment below and update the code to test reportsBouncedGet
        //instance.reportsBouncedGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsEmailcreditsHistoryGet', function() {
      it('should call reportsEmailcreditsHistoryGet successfully', function(done) {
        //uncomment below and update the code to test reportsEmailcreditsHistoryGet
        //instance.reportsEmailcreditsHistoryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsEventlogGet', function() {
      it('should call reportsEventlogGet successfully', function(done) {
        //uncomment below and update the code to test reportsEventlogGet
        //instance.reportsEventlogGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsEventsExportGet', function() {
      it('should call reportsEventsExportGet successfully', function(done) {
        //uncomment below and update the code to test reportsEventsExportGet
        //instance.reportsEventsExportGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsExportGet', function() {
      it('should call reportsExportGet successfully', function(done) {
        //uncomment below and update the code to test reportsExportGet
        //instance.reportsExportGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsGet', function() {
      it('should call reportsGet successfully', function(done) {
        //uncomment below and update the code to test reportsGet
        //instance.reportsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsLinktrackingsExportGet', function() {
      it('should call reportsLinktrackingsExportGet successfully', function(done) {
        //uncomment below and update the code to test reportsLinktrackingsExportGet
        //instance.reportsLinktrackingsExportGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsNotificationsGet', function() {
      it('should call reportsNotificationsGet successfully', function(done) {
        //uncomment below and update the code to test reportsNotificationsGet
        //instance.reportsNotificationsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsPaymentsHistoryGet', function() {
      it('should call reportsPaymentsHistoryGet successfully', function(done) {
        //uncomment below and update the code to test reportsPaymentsHistoryGet
        //instance.reportsPaymentsHistoryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsReferralsGet', function() {
      it('should call reportsReferralsGet successfully', function(done) {
        //uncomment below and update the code to test reportsReferralsGet
        //instance.reportsReferralsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsReferralsPayoutHistoryGet', function() {
      it('should call reportsReferralsPayoutHistoryGet successfully', function(done) {
        //uncomment below and update the code to test reportsReferralsPayoutHistoryGet
        //instance.reportsReferralsPayoutHistoryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsReputationHistoryGet', function() {
      it('should call reportsReputationHistoryGet successfully', function(done) {
        //uncomment below and update the code to test reportsReputationHistoryGet
        //instance.reportsReputationHistoryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsSpamchecksHistoryGet', function() {
      it('should call reportsSpamchecksHistoryGet successfully', function(done) {
        //uncomment below and update the code to test reportsSpamchecksHistoryGet
        //instance.reportsSpamchecksHistoryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reportsSummaryGet', function() {
      it('should call reportsSummaryGet successfully', function(done) {
        //uncomment below and update the code to test reportsSummaryGet
        //instance.reportsSummaryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
